spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: driver-service
          uri: lb://driver-ms
          predicates:
            - Path=/driver-ms/**
          filters:
            - RewritePath=/driver-ms(?<segment>/.*), $\{segment}
            - AddRequestHeader=X-Forwarded-Prefix, /driver-ms
